In [14]:
#Employee Class
class Employee:
    num_of_employees = 0

    #initializing the attributes
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_of_employees += 1

    #Average Salary Method
    def averageSalary(self, employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)
#Full Time Employee Class - Super Class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, employment_type):
        super().__init__(name, family, salary, department)
        self.employment_type = employment_type

# Instances of Employee class
employee1 = Employee("Swathi", "Kothi", 50000, "Senior Software")
employee2 = Employee("Ashwini", "Alakuntla", 80000, "Manager")

# Instances of FulltimeEmployee class
fulltime1 = FulltimeEmployee("Aishwarya", "Tagili", 50000, "Engineering", "FullTime")
fulltime2 = FulltimeEmployee("Sofeen", "Firdouse", 60000, "Marketing", "PartTime")

# Call member functions
employees = [employee1, employee2, fulltime1, fulltime2]
avgSalary = employee1.averageSalary(employees)

print("Total Employees:", Employee.num_of_employees)
print("Average Salary:", avgSalary)

Total Employees: 4
Average Salary: 60000.0


In [15]:
import numpy as np
#generating a vector
vector = np.random.uniform(1, 20, 20)

#reshaping the vector into 4 * 5 matrix
matrix = vector.reshape(4, 5)

print("Original Matrix: \n",matrix)

#finding the index of the max element along axis = 1
indices = np.argmax(matrix, axis=1)

#Create a range of indices for each row
row_indices = np.arange(matrix.shape[0])

#Use advanced indexing to replace max values with 0
matrix[row_indices, indices] = 0

print("Resultant Matrix: \n",matrix)

Original Matrix: 
 [[15.98833226  3.84556477 14.89174452 16.14102157 12.76739049]
 [ 5.13239727  1.5287324   5.08814957 19.9111963   2.57258114]
 [14.90796478  1.28193073 12.0236144   9.57008444  9.21113231]
 [17.89600124 14.35826058 14.97391634 15.37898397 13.85301941]]
Resultant Matrix: 
 [[15.98833226  3.84556477 14.89174452  0.         12.76739049]
 [ 5.13239727  1.5287324   5.08814957  0.          2.57258114]
 [ 0.          1.28193073 12.0236144   9.57008444  9.21113231]
 [ 0.         14.35826058 14.97391634 15.37898397 13.85301941]]
